# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2019, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

version: 2.1

jobs:

  validate_contributor:
    working_directory: ~/nta/nupic.tensorflow
    machine: true
    steps:
      - checkout
      - run:
          name: Validate contributor license
          command: ci/validate-contributor.sh
      - persist_to_workspace:
          root: ~/nta
          paths: nupic.tensorflow

  install_dependencies:
    working_directory: ~/nta/nupic.tensorflow
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: ~/nta
      - restore_cache:
          key: pip-cache-v1-{{ arch }}-{{ checksum "setup.cfg" }}
      - run: pip show flake8-formatter-junit-xml || pip install --user flake8-formatter-junit-xml
      - run: pip show nupic.tensorflow || pip install --user -e ".[dev]"
      - save_cache:
          key: pip-cache-v1-{{ arch }}-{{ checksum "setup.cfg" }}
          paths:
            - ~/.local
            - ~/.cache

  check_style:
    working_directory: ~/nta/nupic.tensorflow
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: ~/nta
      - restore_cache:
          key: pip-cache-v1-{{ arch }}-{{ checksum "setup.cfg" }}
      - run:
          name: Check Style
          command: |
            mkdir -p test_results/flake8
            ~/.local/bin/flake8 --show-source --format junit-xml --output-file test_results/flake8/results.xml src tests
      - store_test_results:
          path: test_results

  test:
    parameters:
      tf_version:
          type: string
    working_directory: ~/nta/nupic.tensorflow
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: ~/nta
      - restore_cache:
          key: pip-cache-v1-{{ arch }}-{{ checksum "setup.cfg" }}
      - run:
          name: Install tensorflow
          command: pip install --user tensorflow==<< parameters.tf_version >>
      - run:
          name: Run python tests
          environment:
            PYTEST_ADDOPTS: --junitxml=test_results/pytest/results.xml --verbose
          command: |
            mkdir -p test_results/pytest
            pytest -ra
      - store_test_results:
          path: test_results

  build:
    working_directory: ~/nta/nupic.tensorflow
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: ~/nta
      - restore_cache:
          key: pip-cache-v1-{{ arch }}-{{ checksum "setup.cfg" }}
      - run:
          name: Build wheel
          environment:
            VERBOSE: 1
          command: |
            python setup.py bdist_wheel
            python setup.py --version > dist/VERSION
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/nta
          paths: nupic.tensorflow/dist


workflows:
  version: 2

  validate-build-test:
    jobs:
      - validate_contributor
      - install_dependencies:
          requires:
            - validate_contributor
      - check_style:
          requires:
            - install_dependencies
      - test:
          matrix:
              parameters:
                  tf_version: ["2.2.3", "2.3.4", "2.4.3", "2.5.1"]
          requires:
            - install_dependencies
      - build:
          requires:
            - check_style
            - test
